name: CI

on:
  push:
    branches: [main]
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/ci.yml'

env:
  CARGO_TERM_COLOR: always
  RUST_NIGHTLY_VERSION: nightly-2025-03-03

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.RUST_NIGHTLY_VERSION }}
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo +${{ env.RUST_NIGHTLY_VERSION }} fmt --all --check

      - name: Add LLVM repository and key
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main" | sudo tee /etc/apt/sources.list.d/llvm-18.list
          echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-20 main" | sudo tee /etc/apt/sources.list.d/llvm-20.list
          sudo apt-get update

      - name: Install LLVM 18 for inkwell
        run: |
          sudo apt-get install -y \
            llvm-18 llvm-18-dev llvm-18-runtime \
            clang-18 libclang-18-dev \
            libpolly-18-dev

      - name: Install LLVM 20 and MLIR for melior
        run: |
          sudo apt-get install -y \
            llvm-20 llvm-20-dev llvm-20-runtime \
            clang-20 libclang-20-dev \
            libmlir-20-dev mlir-20-tools \
            libpolly-20-dev

      - name: Install additional dependencies
        run: |
          sudo apt-get install -y zlib1g-dev libzstd-dev

      - name: Set LLVM environment variables
        run: |
          echo "LLVM_SYS_181_PREFIX=/usr/lib/llvm-18" >> $GITHUB_ENV
          echo "LLVM_SYS_200_PREFIX=/usr/lib/llvm-20" >> $GITHUB_ENV
          echo "MLIR_SYS_200_PREFIX=/usr/lib/llvm-20" >> $GITHUB_ENV
          echo "TABLEGEN_200_PREFIX=/usr/lib/llvm-20" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --all -- -D warnings

      - name: Run tests
        run: cargo test --all
